[[redirects]]
  from = "/*"
  to = "https://runner.codereading.club/index.html"
  status = 301

[build]
  publish = "dist"
  command = "export ELM_HOME=\"elm-stuff\" && yarn test && yarn build"

[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
      paths = ["elm-stuff"]
