[[redirects]]
  from = "https://runner.code-reading.org/*"
  to = "https://runner.codereading.club/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://code-reading-runner.netlify.app/*"
  to = "https://runner.codereading.club/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://runner.codereading.club/index.html"
  status = 200

[build]
  publish = "dist"
  command = "export ELM_HOME=\"elm-stuff\" && yarn test && yarn build"

[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
      paths = ["elm-stuff"]
